FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y stockfish && rm -rf /var/lib/apt/lists/*

COPY requirements_space.txt .
RUN pip install --no-cache-dir -r requirements_space.txt

COPY compare_hf.py .
COPY src/ src/

CMD ["python", "compare_hf.py"]
